name: build and unit_test
on:
  push:
    branches: [ main ]

jobs:
  deploy_infrastructure:
    runs-on: ubuntu-latest
    steps:
    - name: Deploy Compose
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.TEST_HOST }}
        username: ${{ secrets.TEST_USER }}
        password  : ${{ secrets.TEST_PWD }}
        port: ${{ secrets.TEST_PORT }}
        script: |
          cd /bin
          echo "${{ secrets.WORK_ENV }}"> env_file
          sudo rm -r tms
          sudo git clone https://${{ secrets.GIT_PWD }}@github.com/vladzvx/tms
          sudo chmod u+x tms
          sudo mv env_file tms/.env
          cd tms
          sudo docker-compose up -d --build
    
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: |
        cd TMS.Lib.UnitTests
        dotnet restore
        cd ../TMS.FuncTests
        dotnet restore
        
    - name: Build
      run: | 
        cd TMS.Lib.UnitTests
        dotnet build --no-restore
        cd ../TMS.FuncTests
        echo "${{ secrets.TEST_ENV}}" > .env
        echo "${{ secrets.FUNC_ENV}}" > cw.env
        dotnet build --no-restore
    - name: Test
      run: |
        cd TMS.Lib.UnitTests
        dotnet test --no-build --verbosity normal
        cd ../TMS.FuncTests
        dotnet test --no-build --verbosity normal -s ../test.runsettings
